# Generated by Django 2.2.16 on 2021-10-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of titles')),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Categories')),
            ],
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
        migrations.CreateModel(
            name='TitlesGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Genres')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Titles')),
            ],
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(through='categories.TitlesGenres', to='categories.Genres'),
        ),
    ]
