# Generated by Django 2.2.16 on 2021-10-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20211005_1843'),
        ('categories', '0005_auto_20211006_1224'),
    ]

    operations = [
    ]
