# Generated by Django 2.2.16 on 2021-10-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_titles_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
