# Generated by Django 2.2.16 on 2021-10-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20211009_1259'),
        ('categories', '0006_merge_20211009_1509'),
    ]

    operations = [
    ]
