# Generated by Django 2.2.16 on 2021-10-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_merge_20211009_2029'),
        ('categories', '0006_merge_20211008_1513'),
    ]

    operations = [
    ]
