# Generated by Django 2.2.16 on 2021-10-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_merge_20211010_1240'),
        ('categories', '0007_auto_20211009_1847'),
    ]

    operations = [
    ]
